version: "3.8"
services:
  pg_db:
    image: postgres:latest
    container_name: pg_spam_number-detector
    environment:
      - POSTGRES_DB=spam_number_detector
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - 5432:5432
    volumes:
      - pg_db:/var/lib/postgresql/data
volumes:
  pg_db:
    driver: local